#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$(dirname $0)/functions"

case "$1" in
  apps:link)
      set_env
    ;;

  apps:unlink)
      unset_env
    ;;

  help)
    cat<<EOF
    apps:link <app-source> <app-target>, Set in <app-target> variable APP_SOURCE_NAME_URL with access url
    apps:unlink <app-source> <app-target>, Unset in <app-target> APP_SOURCE_NAME_URL
EOF
    ;;

  *)
    exit $DOKKU_NOT_IMPLEMENTED_EXIT
    ;;

esac