#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"

case "$1" in
  apps:link)
    [[ -z $2 ]] && dokku_log_fail "Please specify an app will be created the link"
	[[ -z $3 ]] && dokku_log_fail "Please specify an app which depends"
    APP_SOURCE="$2"; IMAGE_SOURCE_TAG=$(get_running_image_tag $APP_SOURCE); IMAGE_SOURCE=$(get_app_image_name $APP_SOURCE $IMAGE_SOURCE_TAG)
	verify_app_name "$APP_SOURCE"
	APP_TARGET="$3"; IMAGE_TARGET_TAG=$(get_running_image_tag $APP_TARGET); IMAGE_TARGET=$(get_app_image_name $APP_TARGET $IMAGE_TARGET_TAG)
	verify_app_name "$APP_TARGET"

    dokku config:set $APP_TARGET "${APP_SOURCE^^}_URL"=$(dokku url $APP_SOURCE)
    ;;

  apps:unlink)
    [[ -z $2 ]] && dokku_log_fail "Please specify an app will be created the link"
	[[ -z $3 ]] && dokku_log_fail "Please specify an app which depends"
    APP_SOURCE="$2"; IMAGE_SOURCE_TAG=$(get_running_image_tag $APP_SOURCE); IMAGE_SOURCE=$(get_app_image_name $APP_SOURCE $IMAGE_SOURCE_TAG)
	verify_app_name "$APP_SOURCE"
	APP_TARGET="$3"; IMAGE_TARGET_TAG=$(get_running_image_tag $APP_TARGET); IMAGE_TARGET=$(get_app_image_name $APP_TARGET $IMAGE_TARGET_TAG)
	verify_app_name "$APP_TARGET"

    dokku config:unset $APP_TARGET "${APP_SOURCE^^}_URL"
    ;;

  help)
    cat<<EOF
    apps:link <app-source> <app-target>, Set in <app-target> variable APP_SOURCE_NAME_URL with access url
    apps:unlink <app-source> <app-target>, Unset in <app-target> APP_SOURCE_NAME_URL
EOF
    ;;

  *)
    exit $DOKKU_NOT_IMPLEMENTED_EXIT
    ;;

esac