#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE  ]] && set -x

APP_SOURCE="$2";
APP_TARGET="$3";
VAR_SUFFIX="_URL";

set_env() {
	check_apps_args
	dokku config:set $APP_TARGET "${APP_SOURCE^^}$VAR_SUFFIX"=$(dokku url $APP_SOURCE)
}

unset_env() {
	check_apps_args
	dokku config:unset $APP_TARGET "${APP_SOURCE^^}$VAR_SUFFIX"
}

#Verifica se o nome das apps foram informados e se elas existem.
check_apps_args() {
	[[ -z APP_SOURCE ]] && dokku_log_fail "Please specify an app will be created the link"
	[[ -z APP_TARGET ]] && dokku_log_fail "Please specify an app which depends"

	verify_app_name "$APP_SOURCE"
	verify_app_name "$APP_TARGET"
}
