#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$(dirname $0)/functions"

APP=$1
GIT_DIR="$3"
APP_DIR="$DOKKU_ROOT/$APP"
ENV_FILE="requirements.env"
APP_FILE="requirements.app"

if [ -f "$GIT_DIR/$ENV_FILE" ]; then
	cp "$GIT_DIR/$ENV_FILE" "$APP_DIR/$ENV_FILE"
else
	dokku_log_warn "$ENV_FILE not found."
fi

if [ -f "$GIT_DIR/$APP_FILE" ]; then
	cp "$GIT_DIR/$APP_FILE" "$APP_DIR/$APP_FILE"
else
	dokku_log_warn "$APP_FILE not found."
fi

exit 0
